{{- /* Create chart-managed keys secret */ -}}
{{- if .Values.secrets.keys.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.keys.name }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.keys.items }}
{{- if or (ne $k "GOOGLE_APPLICATION_CREDENTIALS") (not $.Values.gcp.workloadIdentity.enabled) }}
  {{ $k }}: "{{ $v }}"
{{- end }}
{{- end }}
{{- end }}
---
{{- /* Create chart-managed migration secret */ -}}
{{- if and .Values.migration.enabled .Values.migration.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.migration.secrets.name }}
type: Opaque
stringData:
{{- range $k, $v := .Values.migration.secrets.items }}
  {{ $k }}: "{{ $v }}"
{{- end }}
{{- end }}
---
{{- /* Create chart-managed summary migration secret */ -}}
{{- if and .Values.summaryMigration.enabled .Values.summaryMigration.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.summaryMigration.secrets.name }}
type: Opaque
stringData:
{{- range $k, $v := .Values.summaryMigration.secrets.items }}
  {{ $k }}: "{{ $v }}"
{{- end }}
{{- end }}
---
{{- /* Create chart-managed files secret */ -}}
{{- if and .Values.secrets.files.create (not .Values.gcp.workloadIdentity.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.files.name }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.files.items }}
  {{ $k }}: |-
{{ $v | indent 4 }}
{{- end }}
{{- end }}
