{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aviator.name" . }}-role
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aviator.name" . }}-rolebinding
subjects:
{{- if .Values.serviceAccount.enabled }}
  {{- if .Values.app.enabled }}
  - kind: ServiceAccount
    name: {{ if .Values.serviceAccount.app.name }}{{ .Values.serviceAccount.app.name }}{{ else }}{{ include "aviator.name" . }}-app{{ end }}
  {{- end }}
  {{- if .Values.worker.enabled }}
  - kind: ServiceAccount
    name: {{ if .Values.serviceAccount.worker.name }}{{ .Values.serviceAccount.worker.name }}{{ else }}{{ include "aviator.name" . }}-worker{{ end }}
  {{- end }}
{{- else }}
  - kind: ServiceAccount
    name: {{ if .Values.gcp.workloadIdentity.enabled }}{{ if .Values.gcp.workloadIdentity.serviceAccountName }}{{ .Values.gcp.workloadIdentity.serviceAccountName }}{{ else }}{{ include "aviator.name" . }}{{ end }}{{ else }}{{ include "aviator.name" . }}{{ end }}
{{- end }}
roleRef:
  kind: Role
  name: {{ include "aviator.name" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
