{{- if .Values.serviceAccount.enabled }}
{{- if .Values.app.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.serviceAccount.app.name }}{{ .Values.serviceAccount.app.name }}{{ else }}{{ include "aviator.name" . }}-app{{ end }}
  {{- if .Values.gcp.workloadIdentity.enabled }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.workloadIdentity.app }}
  {{- end }}
{{- end }}  
---
{{- if .Values.worker.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.serviceAccount.worker.name }}{{ .Values.serviceAccount.worker.name }}{{ else }}{{ include "aviator.name" . }}-worker{{ end }}
  {{- if .Values.gcp.workloadIdentity.enabled }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.workloadIdentity.worker }}
  {{- end }}
{{- end }}    
{{- end }}
